### ISSUE TITLE
As council staff, i need to edit some of the application details, just before signing.

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/pancake-backend#185]
Editing in the rails app
`admin::rebate_forms#edit`

Fields to be editable:
* Applicant's name
* Number of dependants
* Income sum
* Were they living there on 1July.

## NOTE:
"Income sum" is the sum of the applicant's income and one partner's income. 
The backend code currently only saves the income sum, so it's a direct edit of this value.

**Comment by dlouise64** [comment]
closes #493
