### ISSUE TITLE
login to admin sends to app page 

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-backend#78]
This: ![screen shot 2018-05-15 at 1 25 43 pm](https://user-images.githubusercontent.com/36939214/40031369-87b1d3ea-5843-11e8-90bb-8338926e9961.png)
 
to this:

![screen shot 2018-05-15 at 1 25 50 pm](https://user-images.githubusercontent.com/36939214/40031368-878849bc-5843-11e8-9119-cd94bf44974d.png)

When I login with my password on the admin page I am redirected to the main app page

**Comment by Br3nda** [comment]
fixed
